name: llava2
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - expat=2.7.1
  - ld_impl_linux-64=2.44
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libnsl=2.0.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.18
  - pip=25.2
  - pthread-stubs=0.3
  - python=3.12.12
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.50.2
  - tk=8.6.15
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - absl-py==2.3.1
      - alembic==1.17.0
      - annotated-doc==0.0.3
      - annotated-types==0.7.0
      - anyio==4.11.0
      - astor==0.8.1
      - attrs==25.4.0
      - beautifulsoup4==4.14.2
      - black==25.9.0
      - blinker==1.9.0
      - cachetools==6.2.1
      - certifi==2025.10.5
      - cffi==2.0.0
      - cfgv==3.4.0
      - charset-normalizer==3.4.4
      - clearml==2.0.3rc1
      - click==8.3.0
      - cloudpickle==3.1.1
      - colorama==0.4.6
      - colorlog==6.10.1
      - contourpy==1.3.3
      - crc32c==2.8
      - cryptography==46.0.3
      - cycler==0.12.1
      - databricks-sdk==0.70.0
      - deprecated==1.2.18
      - distlib==0.4.0
      - docker==7.1.0
      - donfig==0.8.1.post1
      - einops==0.8.1
      - fastapi==0.120.0
      - filelock==3.20.0
      - fire==0.7.1
      - flask==3.1.2
      - flask-cors==6.0.1
      - fonttools==4.60.1
      - fsspec==2025.9.0
      - furl==2.1.4
      - gdown==5.2.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-auth==2.41.1
      - graphene==3.4.3
      - graphql-core==3.2.6
      - graphql-relay==3.2.0
      - greenlet==3.2.4
      - grpcio==1.76.0
      - gunicorn==23.0.0
      - h11==0.16.0
      - h5py==3.15.1
      - hf-xet==1.2.0
      - huggingface-hub==0.36.0
      - humanize==4.14.0
      - identify==2.6.15
      - idna==3.11
      - imagecodecs==2025.8.2
      - imageio==2.37.0
      - importlib-metadata==8.7.0
      - itk==5.4.4.post1
      - itk-core==5.4.4.post1
      - itk-filtering==5.4.4.post1
      - itk-io==5.4.4.post1
      - itk-numerics==5.4.4.post1
      - itk-registration==5.4.4.post1
      - itk-segmentation==5.4.4.post1
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - joblib==1.5.2
      - json-tricks==3.17.3
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - lmdb==1.7.5
      - lpips==0.1.4
      - mako==1.3.10
      - markdown==3.9
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - mdurl==0.1.2
      - ml-dtypes==0.5.3
      - mlflow==3.5.1
      - mlflow-skinny==3.5.1
      - mlflow-tracing==3.5.1
      - monai==1.5.1
      - mpmath==1.3.0
      - mypy-extensions==1.1.0
      - networkx==3.5
      - nibabel==5.3.2
      - ninja==1.13.0
      - nni==3.0
      - nodeenv==1.9.1
      - numcodecs==0.16.3
      - numpy==2.3.4
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-ml-py==13.580.82
      - nvidia-nccl-cu11==2.21.5
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu11==11.8.86
      - nvidia-nvtx-cu12==12.1.105
      - onnx==1.19.1
      - openslide-bin==4.0.0.8
      - openslide-python==1.4.2
      - opentelemetry-api==1.38.0
      - opentelemetry-proto==1.38.0
      - opentelemetry-sdk==1.38.0
      - opentelemetry-semantic-conventions==0.59b0
      - optuna==4.5.0
      - orderedmultidict==1.0.1
      - packaging==25.0
      - pandas==2.3.3
      - pathlib2==2.3.7.post1
      - pathspec==0.12.1
      - pillow==12.0.0
      - platformdirs==4.5.0
      - polars==1.34.0
      - polars-runtime-32==1.34.0
      - pre-commit==4.3.0
      - prettytable==3.16.0
      - protobuf==6.33.0
      - psutil==7.1.2
      - pyamg==5.2.1
      - pyarrow==21.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.23
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - pydicom==3.0.1
      - pygments==2.19.2
      - pyjwt==2.10.1
      - pynrrd==1.1.3
      - pyparsing==3.2.5
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.1
      - pythonwebhdfs==0.2.3
      - pytokens==0.2.0
      - pytorch-ignite==0.4.11
      - pytz==2025.2
      - pyyaml==6.0.3
      - referencing==0.37.0
      - regex==2025.10.23
      - requests==2.32.5
      - responses==0.25.8
      - rich==14.2.0
      - rpds-py==0.28.0
      - rsa==4.9.1
      - ruamel-yaml==0.18.16
      - ruamel-yaml-clib==0.2.14
      - ruff==0.14.2
      - safetensors==0.6.2
      - schema==0.7.8
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.16.2
      - shellingham==1.5.4
      - simpleitk==2.5.2
      - simplejson==3.20.2
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.8
      - sqlalchemy==2.0.44
      - sqlparse==0.5.3
      - starlette==0.48.0
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.4
      - termcolor==3.1.0
      - threadpoolctl==3.6.0
      - tifffile==2025.10.16
      - timm==1.0.21
      - tokenizers==0.22.1
      - torch==2.7.1+cu118
      - torchaudio==2.7.1+cu118
      - torchio==0.20.23
      - torchvision==0.22.1+cu118
      - tqdm==4.67.1
      - transformers==4.57.1
      - triton==3.3.1
      - typeguard==4.1.2
      - typer==0.20.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - unidep==1.0.1
      - urllib3==2.5.0
      - uvicorn==0.38.0
      - virtualenv==20.35.3
      - wcwidth==0.2.14
      - websockets==15.0.1
      - werkzeug==3.1.3
      - wrapt==1.17.3
      - zarr==3.1.3
      - zipp==3.23.0
