name: /gpfs/scratch/gs4342/conda_envs/head_ct
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2025.9.9=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=24.2=py38h06a4308_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.8.18=h955ad1f_0
  - readline=8.3=hc2a1206_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.44.0=py38h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - absl-py==2.3.1
      - alembic==1.14.1
      - anyio==4.5.2
      - appdirs==1.4.4
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asciitree==0.3.3
      - astor==0.8.1
      - asttokens==3.0.0
      - async-lru==2.0.4
      - attrs==25.3.0
      - babel==2.17.0
      - backcall==0.2.0
      - beautifulsoup4==4.14.2
      - bleach==6.1.0
      - blinker==1.8.2
      - cachetools==5.5.2
      - certifi==2025.10.5
      - cffi==1.17.1
      - charset-normalizer==3.4.3
      - clearml==2.0.3rc0
      - click==8.1.8
      - cloudpickle==3.1.1
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - colorlog==6.9.0
      - comm==0.2.3
      - contourpy==1.1.1
      - cycler==0.12.1
      - databricks-sdk==0.67.0
      - debugpy==1.8.17
      - decorator==5.2.1
      - defusedxml==0.7.1
      - deprecated==1.2.18
      - docker==7.1.0
      - docker-pycreds==0.4.0
      - einops==0.8.1
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - fairscale==0.4.13
      - fasteners==0.20
      - fastjsonschema==2.21.2
      - filelock==3.11.0
      - fire==0.7.1
      - flask==3.0.3
      - flatbuffers==25.9.23
      - fonttools==4.57.0
      - fqdn==1.5.1
      - fsspec==2025.3.0
      - furl==2.1.4
      - gdown==5.2.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-auth==2.41.1
      - google-auth-oauthlib==1.0.0
      - graphene==3.4.3
      - graphql-core==3.2.6
      - graphql-relay==3.2.0
      - greenlet==3.1.1
      - grpcio==1.70.0
      - gunicorn==23.0.0
      - h11==0.16.0
      - h5py==3.11.0
      - hf-xet==1.1.10
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.35.3
      - humanfriendly==10.0
      - idna==3.10
      - imagecodecs==2023.3.16
      - imageio==2.35.1
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - ipykernel==6.29.5
      - ipython==8.12.3
      - ipywidgets==8.1.7
      - isoduration==20.11.0
      - itk==5.4.4
      - itk-core==5.4.4
      - itk-filtering==5.4.4
      - itk-io==5.4.4
      - itk-numerics==5.4.4
      - itk-registration==5.4.4
      - itk-segmentation==5.4.4
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.4.2
      - json-tricks==3.17.3
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.8.1
      - jupyter-events==0.10.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.8
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - lmdb==1.7.3
      - lpips==0.1.4
      - mako==1.3.10
      - markdown==3.7
      - markupsafe==2.1.5
      - matplotlib==3.7.1
      - matplotlib-inline==0.1.7
      - mistune==3.1.4
      - mlflow==2.17.2
      - mlflow-skinny==2.17.2
      - monai==1.3.2
      - mpmath==1.3.0
      - nbclient==0.10.1
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.1
      - nibabel==5.2.1
      - ninja==1.13.0
      - nni==3.0
      - notebook==7.3.3
      - notebook-shim==0.2.4
      - numcodecs==0.12.1
      - numpy==1.24.4
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py==13.580.82
      - nvidia-nccl-cu11==2.20.5
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu11==11.8.86
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.3.1
      - onnx==1.17.0
      - onnxruntime==1.19.2
      - openslide-python==1.4.1
      - opentelemetry-api==1.33.1
      - opentelemetry-sdk==1.33.1
      - opentelemetry-semantic-conventions==0.54b1
      - optuna==4.5.0
      - orderedmultidict==1.0.1
      - overrides==7.7.0
      - packaging==24.2
      - pandas==1.5.3
      - pandocfilters==1.5.1
      - parso==0.8.5
      - pathlib2==2.3.7.post1
      - pathtools==0.1.2
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==10.4.0
      - pkgutil-resolve-name==1.3.10
      - platformdirs==4.3.6
      - polars==1.8.2
      - prettytable==3.11.0
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.52
      - protobuf==4.25.8
      - psutil==7.1.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==17.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.23
      - pydicom==2.4.4
      - pygments==2.19.2
      - pyjwt==2.9.0
      - pynrrd==1.1.3
      - pyparsing==3.1.4
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - python-json-logger==4.0.0
      - pythonwebhdfs==0.2.3
      - pytorch-ignite==0.4.11
      - pytz==2025.2
      - pywavelets==1.4.1
      - pyyaml==6.0.2
      - pyzmq==27.1.0
      - referencing==0.35.1
      - regex==2024.11.6
      - requests==2.32.4
      - requests-oauthlib==2.0.0
      - responses==0.25.8
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.20.1
      - rsa==4.9.1
      - safetensors==0.5.3
      - schema==0.7.7
      - scikit-image==0.21.0
      - scikit-learn==1.3.0
      - scipy==1.10.1
      - send2trash==1.8.3
      - sentry-sdk==2.40.0
      - setproctitle==1.3.7
      - setuptools==67.7.2
      - simplejson==3.20.2
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.7
      - sqlalchemy==2.0.43
      - sqlparse==0.5.3
      - stack-data==0.6.3
      - sympy==1.13.3
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - termcolor==1.1.0
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - tifffile==2023.7.10
      - timm==1.0.12
      - tinycss2==1.2.1
      - tokenizers==0.19.1
      - tomli==2.2.1
      - torch==2.4.1+cu118
      - torchaudio==2.4.1+cu118
      - torchmetrics==0.10.3
      - torchvision==0.19.1+cu118
      - tornado==6.4.2
      - tqdm==4.66.1
      - traitlets==5.14.3
      - transformers==4.40.2
      - triton==3.0.0
      - typeguard==4.1.2
      - types-python-dateutil==2.9.0.20241206
      - typing-extensions==4.13.2
      - uri-template==1.3.0
      - urllib3==2.2.3
      - wandb==0.13.9
      - wcwidth==0.2.14
      - webcolors==24.8.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - websockets==13.1
      - werkzeug==3.0.6
      - widgetsnbextension==4.0.14
      - wrapt==1.17.3
      - yacs==0.1.8
      - zarr==2.16.1
      - zipp==3.20.2
prefix: /gpfs/scratch/gs4342/conda_envs/head_ct
